# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 618692b1f484647cdad5e44f405a236bb1b745223028b37d8e77ff1f0015719f2446dba61563ce8c14d9478e429e1e88ce5e01cd531107f6db7a3526027b089f

test:
  secret_key_base: 7649e0fafe1ba7155e5bd18f070f460b83d29fc421d1da4feac1821b6c5335f71fa2305662917103ef75e38a2373bb6a4474b83fc14d896ea4216c2cce3015d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
